### ISSUE TITLE
Installer fails if there are no organizations defined in the system

### ISSUE THREAD

**Issue by mkanoor** [ansible/automation_services_catalog_client#12]
The installer fails when there are no organizations defined in the tower

https://github.com/ansible/automation_services_catalog_client/blob/cce73477670ff59b2891722d82058525e1bc7bbe/roles/automation_services_catalog_client/tasks/generate_token.yml#L38

Since the previous tasks have no_log : true its difficult to diagnose the issue since nothing is logged.

If we can check if there are no organizations and generate an error message for the user it would help

**Comment by Spredzy** [comment]
How is it possible to have a user assigned to no organization in Tower ?

When creating a user, the Organization is a mandatory parameter (A Default organization is made available upon install). How can we end up with no org ?

@mkanoor how can I reproduce ?

**Comment by wenottingham** [comment]
The system administrator is generally not assigned to any org (while retaining rights to all orgs).

**Comment by Spredzy** [comment]
Fixed.
