### ISSUE TITLE
remove rhc-worker-playbook rpm during install

### ISSUE THREAD

**Issue by mkanoor** [ansible/automation_services_catalog_client#16]
On a RHEL 8.4 the following 2 RPM would already be installed

- rhc
- rhc-worker-playbook

When we activate the rhcd service in the customers environment for the catalog worker the playbook worker would also be activated and that VM would be targeted from the cloud to run insights playbook.

Since we only need the catalog worker we should remove the play book worker by removing the rhc-worker-playbook RPM during our install.

**Comment by Spredzy** [comment]
Based on my understanding of the problem, this isn't suited here but rather at the spec level using `obsoletes: rhc-worker-playbook`.

Just to clarify, when we install `rhc-catalog-worker` we want to ensure `rhc-worker-playbook` is removed, is that correct ?

**Comment by mkanoor** [comment]
@Spredzy  Since the rhc-worker-playbook would be present in RHEL 8.4 by default, the customer doesn't know that they signed up for adding a catalog worker by running our role and then the existing rhc-worker-playbook started communicating with the cloud asking it for playbooks to run on that VM. I am not sure if the customer knows at that point that playbooks are going to be run on this VM, the provisioned the VM just to run the rhc-catalog-worker

**Comment by mkanoor** [comment]
@Spredzy If we bundle it in our spec then we are basically saying we have conflicts with the other package. In our case we don't have a conflict if a customer wants to use them in way where they would like to use both the workers they should be able to do it. It is more of a customer buy-in than conflicts between the 2 workers.
